const med_word = [
    { word: "apple", hint: "A sweet fruit that keeps the doctor away." },
    { word: "bread", hint: "A staple food made from flour and water." },
    { word: "grape", hint: "A small fruit that comes in bunches." },
    { word: "clock", hint: "It tells you the time throughout the day." },
    { word: "piano", hint: "A musical instrument with keys." },
    { word: "chair", hint: "You sit on it for comfort." },
    { word: "flame", hint: "A visible part of a fire." },
    { word: "table", hint: "Furniture with a flat top surface." },
    { word: "cloud", hint: "White and fluffy, floating in the sky." },
    { word: "light", hint: "It brightens up the dark." },
    { word: "stone", hint: "Hard and found on the ground." },
    { word: "water", hint: "Essential for life and found in rivers." },
    { word: "truck", hint: "A vehicle used to transport goods." },
    { word: "dance", hint: "A movement to music." },
    { word: "flute", hint: "A wind instrument that makes music." },
    { word: "lemon", hint: "A yellow citrus fruit." },
    { word: "smile", hint: "A facial expression of happiness." },
    { word: "bread", hint: "A baked food often used for sandwiches." },
    { word: "plant", hint: "Green and grows in soil." },
    { word: "candy", hint: "A sweet treat enjoyed by many." },
    { word: "house", hint: "A place where people live." },
    { word: "grass", hint: "It covers the ground and is green." },
    { word: "field", hint: "An open area of land." },
    { word: "river", hint: "Flows into lakes or oceans." },
    { word: "night", hint: "The time when it is dark." },
    { word: "arrow", hint: "A pointed weapon or direction sign." },
    { word: "cycle", hint: "A repeated sequence of events." },
    { word: "beach", hint: "Where sand meets the sea." },
    { word: "toast", hint: "Bread that has been browned by heat." },
    { word: "space", hint: "Where the stars and planets exist." },
    { word: "flour", hint: "Used for baking bread and cakes." },
    { word: "chain", hint: "A series of linked metal rings." },
    { word: "sheep", hint: "An animal with wool." },
    { word: "grill", hint: "Used to cook food outdoors." },
    { word: "glove", hint: "Worn to protect or warm hands." },
    { word: "steam", hint: "Hot vapor rising from boiling water." },
    { word: "fruit", hint: "Sweet and grows on trees or plants." },
    { word: "smoke", hint: "Rises from fire or a chimney." },
    { word: "leash", hint: "Used to control a dog during a walk." },
    { word: "zebra", hint: "A black-and-white striped animal." },
    { word: "stone", hint: "A small piece of rock." },
    { word: "frost", hint: "Forms on cold surfaces in winter." },
    { word: "purse", hint: "Used to carry money and small items." },
    { word: "plane", hint: "Flies high and carries passengers." },
    { word: "field", hint: "An open space of grass or crops." },
    { word: "flask", hint: "Used to carry liquids on the go." },
    { word: "spear", hint: "A long weapon with a sharp tip." },
    { word: "shade", hint: "Blocks sunlight to keep things cool." },
    { word: "latch", hint: "Keeps a door closed securely." },
    { word: "plant", hint: "Grows and thrives in sunlight." },
    { word: "berry", hint: "Small, juicy fruit often red or blue." },
    { word: "daisy", hint: "A flower with white petals and a yellow center." },
    { word: "flint", hint: "A hard stone used to start fires." },
    { word: "cream", hint: "Thick and rich, often on desserts." },
    { word: "spice", hint: "Adds flavor and aroma to food." },
    { word: "crown", hint: "Worn by kings and queens." },
    { word: "eagle", hint: "A bird with sharp eyes and strong wings." },
    { word: "grape", hint: "A small fruit that grows in clusters." },
    { word: "torch", hint: "Used to light the way in darkness." },
    { word: "flame", hint: "The glowing part of a fire." },
    { word: "pouch", hint: "A small bag for carrying items." },
    { word: "paint", hint: "Used to add color to surfaces." },
    { word: "frost", hint: "White ice crystals on cold mornings." },
    { word: "drift", hint: "To move slowly with the wind or water." },
    { word: "cliff", hint: "A steep rock face near water." },
    { word: "shell", hint: "Protective cover for some animals." },
    { word: "honey", hint: "Sweet and made by bees." },
    { word: "brick", hint: "A block used for building walls." },
    { word: "storm", hint: "Rain, wind, and thunder combined." },
    { word: "teeth", hint: "Used for chewing food." },
    { word: "arrow", hint: "A symbol or weapon with a pointed tip." },
    { word: "shark", hint: "A predator in the ocean." },
    { word: "vivid", hint: "Bright and full of color." },
    { word: "spoon", hint: "Used to eat soup or cereal." },
    { word: "orbit", hint: "The path of a planet or moon." },
    { word: "giant", hint: "Very large and powerful." },
    { word: "piano", hint: "An instrument with black and white keys." },
    { word: "raven", hint: "A large black bird with a cawing sound." },
    { word: "bread", hint: "A staple food made from dough." },
    { word: "charm", hint: "A small object thought to bring luck." },
    { word: "cable", hint: "Used to transmit electricity or data." },
    { word: "apple", hint: "A fruit often red or green." },
    { word: "fence", hint: "A barrier around a yard or field." },
    { word: "glass", hint: "Transparent and used in windows." },
    { word: "loyal", hint: "Faithful and trustworthy." },
    { word: "grape", hint: "A fruit used to make wine." },
    { word: "pride", hint: "A feeling of deep satisfaction." },
    { word: "shiny", hint: "Reflects light brightly." },
    { word: "beast", hint: "A wild and dangerous animal." },
    { word: "scent", hint: "A smell, often pleasant." },
    { word: "brick", hint: "A building block made of clay." },
    { word: "plant", hint: "Grows from soil and needs water." },
    { word: "smoke", hint: "Rises from fire or chimneys." },
    { word: "weave", hint: "To make fabric by crossing threads." },
    { word: "stone", hint: "A hard mineral from the earth." },
    { word: "flame", hint: "Part of a fire that glows and burns." },
    { word: "crown", hint: "Worn by royalty as a symbol of power." },
    { word: "shrub", hint: "A small bushy plant." },
    { word: "harsh", hint: "Rough or unpleasant to experience." },
    { word: "bench", hint: "A long seat often found in parks." },
    { word: "clash", hint: "A conflict or disagreement." },
    { word: "flask", hint: "A container for holding liquids." },
    { word: "steam", hint: "Hot vapor rising from boiling water." },
    { word: "spark", hint: "A small burst of fire or light." },
    { word: "grill", hint: "Used for cooking food over a flame." },
    { word: "ridge", hint: "A long, narrow hilltop." },
    { word: "dream", hint: "Thoughts and visions while asleep." },
    { word: "plank", hint: "A flat piece of wood or material." },
    { word: "chill", hint: "A feeling of coldness." },
    { word: "vowel", hint: "A letter like A, E, I, O, or U." },
    { word: "cliff", hint: "A steep rock face, often near the sea." },
    { word: "brick", hint: "Used for construction and building walls." },
    { word: "ocean", hint: "A vast body of saltwater." },
    { word: "flute", hint: "A wind instrument with holes to play." },
    { word: "giant", hint: "Something very large or huge." },
    { word: "flour", hint: "A powder used in baking." },
    { word: "sheep", hint: "An animal raised for its wool." },
    { word: "smile", hint: "A happy expression on the face." },
];
