export const sample_word = [
    { word: "book", hint: "Often found on a shelf, it's full of knowledge or stories." },
    { word: "coin", hint: "It's small, round, and jingles in your pocket." },
    { word: "moon", hint: "It has phases and lights up the night." },
    { word: "love", hint: "Something you feel but cannot hold." },
    { word: "rain", hint: "It makes the ground wet and feeds the plants." },
    { word: "lamp", hint: "A companion to darkness, it glows softly." },
    { word: "fish", hint: "It swims but has no feet or hands." },
    { word: "tree", hint: "It grows tall, stands still, and has rings inside." },
    { word: "star", hint: "A tiny speck in the sky that shines." },
    { word: "time", hint: "You can't see it, but it keeps everything moving." },
    { word: "game", hint: "Played for fun, but sometimes for competition too." },
    { word: "wind", hint: "It moves but cannot be seen." },
    { word: "fire", hint: "It's warm, bright, and devours what it touches." },
    { word: "milk", hint: "A white drink that comes from an animal." },
    { word: "gold", hint: "A shiny metal that's always in demand." },
    { word: "rock", hint: "Solid, silent, and has been around forever." },
    { word: "lake", hint: "A resting place for water, surrounded by land." },
    { word: "desk", hint: "Where work gets done, or at least tried." },
    { word: "door", hint: "It swings or slides to let you in or out." },
    { word: "snow", hint: "It's cold, white, and falls quietly." },
    { word: "bird", hint: "It sings but does not speak." },
    { word: "frog", hint: "It hops and often hides near water." },
    { word: "wave", hint: "It's both in the ocean and in a friendly greeting." },
    { word: "home", hint: "A place where your heart feels safe." },
    { word: "cake", hint: "It's sweet, layered, and often has candles." },
    { word: "boat", hint: "It floats but cannot swim." },
    { word: "song", hint: "A story told in notes and rhythm." },
    { word: "nest", hint: "Built high or low, it's a safe place for new life." },
    { word: "belt", hint: "Keeps things together but goes unnoticed." },
    { word: "ring", hint: "A circle that holds great significance." },
    { word: "dust", hint: "It's tiny and always finds its way back." },
    { word: "veil", hint: "It hides but doesn't fully conceal." },
    { word: "bark", hint: "It's tough on the outside but protects what's inside." },
    { word: "gift", hint: "It's given, not taken, and brings a smile." },
    { word: "king", hint: "Rules without a weapon, leads without a map." },
    { word: "pond", hint: "A mirror for the sky, still and shallow." },
    { word: "salt", hint: "It enhances but doesn't overpower." },
    { word: "path", hint: "It guides, but you must choose to follow." },
    { word: "rope", hint: "Twisted strands that hold things together." },
    { word: "film", hint: "It tells stories without turning a page." },
    { word: "echo", hint: "It's your voice, but from somewhere else." },
    { word: "leaf", hint: "It's green in life but brown in death." },
    { word: "dusk", hint: "It signals the end of a bright day." },
    { word: "seed", hint: "It holds potential for something great." },
    { word: "jade", hint: "A green gem that's smooth and cool." },
    { word: "pear", hint: "A fruit with curves and a sweet heart." },
    { word: "arch", hint: "A curve that holds weight or marks a path." },
    { word: "grid", hint: "A pattern of lines crossing each other." },
    { word: "band", hint: "It holds together or plays together." },
    { word: "vest", hint: "A garment that keeps your core warm." },
    { word: "toad", hint: "A warty friend of ponds and marshes." },
    { word: "clay", hint: "Soft and moldable, it hardens with fire." },
    { word: "rice", hint: "A staple food that's small but filling." },
    { word: "pear", hint: "A fruit that's neither apple nor orange." },
    { word: "drum", hint: "It makes music with just a beat." },
    { word: "wing", hint: "It helps some to fly and others to dream." },
    { word: "nest", hint: "Where feathers and eggs come together." },
    { word: "silk", hint: "Soft as a whisper, spun by a tiny creature." },
    { word: "lion", hint: "It roars but doesn't purr." },
    { word: "coal", hint: "It fuels fire but turns to ash." },
    { word: "barn", hint: "A shelter for the quiet workers of the farm." },
    { word: "rope", hint: "It's long, strong, and helps you climb." },
    { word: "bead", hint: "Small and colorful, strung together with care." },
    { word: "mist", hint: "A soft, wet veil for the morning." },
    { word: "iron", hint: "Hard, strong, and a tool of the past." },
    { word: "reef", hint: "A home under the sea, teeming with life." },
    { word: "veil", hint: "A cover that's both seen and unseen." },
    { word: "lime", hint: "A citrus fruit that adds zest to life." },
    { word: "yarn", hint: "It tells a tale or weaves a fabric." },
    { word: "glow", hint: "A soft light that warms the dark." },
    { word: "beam", hint: "A ray of light or a sturdy support." },
    { word: "snow", hint: "White and silent, it blankets the world." },
    { word: "kite", hint: "It dances with the wind but needs a string." },
    { word: "mint", hint: "Fresh, cool, and often green." },
    { word: "wave", hint: "It rolls in endlessly, greeting the shore." },
    { word: "rose", hint: "Beautiful and fragrant, but watch for thorns." },
    { word: "grid", hint: "A network of lines that organizes." },
    { word: "bell", hint: "It rings to mark time or call attention." },
    { word: "dove", hint: "A bird of peace, white and serene." },
    { word: "soap", hint: "It cleans but doesn't stay clean itself." },
    { word: "jade", hint: "Precious and green, a stone of the east." },
    { word: "rust", hint: "The color of decay on metal." },
    { word: "wave", hint: "It crashes but never breaks completely." },
    { word: "lamp", hint: "It brightens the corner where it stands." },
    { word: "vine", hint: "It climbs but stays rooted." },
    { word: "maze", hint: "A path that's not always straightforward." },
    { word: "plum", hint: "Sweet, round, and often purple." },
    { word: "twig", hint: "A small branch, light but strong." },
    { word: "flax", hint: "A plant that gives both fiber and oil." },
    { word: "fern", hint: "A green plant with feathery fronds." },
    { word: "knit", hint: "To loop yarn into fabric." },
    { word: "bark", hint: "It's rough and protects the tree." }
];